route:
  group_by: ["Alertname"]
  receiver: email-me

receivers:
  - name: email-me
    email_configs:
      - to: xxxxxxx@gmail.com
        from: xxxxxxx@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: xxxxxxx@gmail.com
        auth_identity: xxxxxxx@gmail.com
        auth_password: xxxxxxxxxxxxxxxx
        send_resolved: true
