route:
  group_by: ["Alertname"]
  receiver: telegram-gmail

receivers:
  - name: telegram-gmail
    telegram_configs:
      - send_resolved: true
        bot_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx #To change
        chat_id: xxxxxxxxxxxx #To change
        api_url: https://api.telegram.org
        parse_mode: "HTML"

    email_configs:
      - to: xxxxxxxx@gmail.com
        from: xxxxxxx@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: xxxxxxx@gmail.com
        auth_identity: xxxxxxx@gmail.com
        auth_password: xxxxxxxxxxxxxxxxxxxxxxxxxxx
        send_resolved: true
