apiVersion: v1alpha1
sts-region: us-east-2
customNamespace:
  - name: MCPRDSMetrics
    namespace: MCPRDSMetrics
    regions:
      - us-east-2
    roles:
      - roleArn: "arn:aws:iam::164957818006:role/rds-role"
    metrics:
      - name: BinLogDiskUsage
        statistics:
          - Average
        period: 300
        length: 300
        nilToZero: true
      - name: ConnectionAttempts
        statistics:
          - Average
        period: 300
        length: 300
      - name: CPUUtilization
        statistics:
          - Average
        period: 300
        length: 300
      - name: CPUCreditUsage
        statistics:
          - Average
        period: 300
        length: 300
      - name: CPUCreditBalance
        statistics:
          - Average
        period: 300
        length: 300
      - name: DatabaseConnections
        statistics:
          - Average
        period: 300
        length: 300
      - name: EBSIOBalance%
        statistics:
          - Average
        period: 300
        length: 300
      - name: FreeableMemory
        statistics:
          - Average
        period: 300
        length: 300
      - name: FreeLocalStorage
        statistics:
          - Average
        period: 300
        length: 300
      - name: FreeStorageSpace
        statistics:
          - Average
        period: 300
        length: 300
      - name: ReadIOPS
        statistics:
          - Average
        period: 300
        length: 300
      - name: ReadLatency
        statistics:
          - Average
        period: 300
        length: 300
      - name: SwapUsage
        statistics:
          - Average
        period: 300
        length: 300
      - name: WriteIOPS
        statistics:
          - Average
        period: 300
        length: 300
      - name: WriteLatency
        statistics:
          - Average
        period: 300
        length: 300
      - name: DBInstaces
        statistics:
          - Average
        period: 300
        length: 300
      - name: AllocatedStorage
        statistics:
          - Average
        period: 300
        length: 300
        nilToZero: true
