global:
  scrape_interval: 1m
  evaluation_interval: 10s
  external_labels:
    monitor: "prom3rds"

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: "node"
    ec2_sd_configs:
      - region: us-east-2
        access_key: XXXXXXXXXXXXXXXX
        secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        regex: "(.*)" #default value
        target_label: _address_
        replacement: "${1}:9100"
        # action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance

  - job_name: "rds"
    scrape_interval: 100s
    scrape_timeout: 80s
    metrics_path: "/basic"
    params:
      format: ["prometheus"]
    honor_labels: true
    static_configs:
      - targets:
          - "prom2rds.cldchisvcpw5.us-east-2.rds.amazonaws.com:9042"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_instance
      - source_labels: [__param_instance]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9042"
