lobal:
  scrape_interval: 1m
  evaluation_interval: 10s
  external_labels:
    monitor: "prom_stack"

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: "node"
    ec2_sd_configs:
      - region: us-east-2
        access_key: XXXXXXXXXXXXXXXX
        secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXX
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        regex: "(.*)" #default value
        target_label: _address_
        replacement: "${1}:9100"
        # action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
