---
instances:
  - region: us-east-2
    instance: myrds
    aws_access_key: XXXXXXXXXXXXXXXXX
    aws_secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXX
    disable_basic_metrics: true
    disable_enhanced_metrics: false
